name: On Release -- Push NuGet

on:
  release:
    types: [published]

jobs:
  ci:
    uses: magmaworks/actions/.github/workflows/on-release.yml@main
    secrets: inherit
    with:
      dotnet: '8.0.x'
